/**
 * Source Import Agent — operator-facing summary writer.
 *
 * Emits `IMPORT_SUMMARY.md` at the workspace root capturing:
 *   - source identity + version
 *   - detection report
 *   - security report (risk class + top findings)
 *   - fork registration id
 *   - next-step CLI commands
 *
 * Plain Markdown, no templating engine, no emoji (match the Custom
 * Workspace Starter docs style).
 */

import fs from "node:fs";
import path from "node:path";
import type { SourceImportManifest } from "./types.js";

export interface WriteImportSummaryInput {
  forkPath: string;
  summaryRelativePath: string;
  manifest: SourceImportManifest;
}

function sourceHeading(manifest: SourceImportManifest): string {
  const src = manifest.source;
  if (src.kind === "github-repo") {
    return `GitHub repo \`${src.repo.owner}/${src.repo.repo}\` (default branch \`${src.defaultBranch}\`)`;
  }
  return `skills.sh skill \`${src.skillId}\` @ \`${src.version}\` — _${src.title}_ by ${src.author}`;
}

function securitySection(manifest: SourceImportManifest): string {
  const sec = manifest.security;
  const header = `Risk class: **${sec.riskClass}**  \nFindings: ${sec.findings.length} (inspected ${sec.filesInspected} files, ${sec.bytesInspected} bytes)`;
  if (sec.findings.length === 0) {
    return `${header}\n\nNo pattern-based security findings surfaced.`;
  }
  const rows = sec.findings
    .slice(0, 20)
    .map(
      (f) =>
        `| ${f.severity} | ${f.category} | \`${f.path}\` | ${f.message.replace(/\|/g, "\\|")} |`,
    )
    .join("\n");
  const hiddenNote =
    sec.findings.length > 20
      ? `\n\n_(${sec.findings.length - 20} additional finding(s) omitted for brevity — see \`.growthub-fork/source-import.json\`.)_`
      : "";
  return (
    `${header}\n\n` +
    `| Severity | Category | Path | Message |\n` +
    `| --- | --- | --- | --- |\n` +
    `${rows}${hiddenNote}`
  );
}

function detectionSection(manifest: SourceImportManifest): string {
  const d = manifest.detection;
  const scripts = Object.entries(d.scripts)
    .map(([k, v]) => `  - \`${k}\`: \`${v}\``)
    .join("\n");
  return [
    `- Framework: \`${d.framework}\``,
    `- Package manager: \`${d.packageManager}\``,
    `- App root: \`${d.appRoot}\``,
    `- Monorepo: ${d.isMonorepo ? "yes" : "no"}`,
    `- Env files: ${d.envFiles.length ? d.envFiles.map((e) => `\`${e}\``).join(", ") : "_none detected_"}`,
    `- Detection confidence: ${d.confidence}`,
    scripts ? `- Scripts:\n${scripts}` : "- Scripts: _none detected_",
    d.warnings.length
      ? `- Warnings:\n${d.warnings.map((w) => `  - ${w}`).join("\n")}`
      : "- Warnings: _none_",
  ].join("\n");
}

function nextStepsSection(manifest: SourceImportManifest): string {
  return [
    `1. Inspect the imported payload at \`./${manifest.payloadRelativePath}/\`.`,
    `2. Review the append-only trace at \`./.growthub-fork/trace.jsonl\`.`,
    `3. Run \`growthub kit fork status\` to see drift vs. the starter baseline.`,
    `4. Run \`growthub kit fork sync\` to heal the workspace when the starter upstream ships a new version.`,
  ].join("\n");
}

/**
 * Write the operator-facing `IMPORT_SUMMARY.md`. Returns the absolute
 * path to the written file.
 */
export function writeImportSummary(input: WriteImportSummaryInput): string {
  const { forkPath, summaryRelativePath, manifest } = input;
  const summaryPath = path.resolve(forkPath, summaryRelativePath);

  const body = [
    `# Source Import Summary`,
    ``,
    `**Import ID:** \`${manifest.importId}\`  `,
    `**Imported at:** ${manifest.importedAt}  `,
    `**Source kind:** \`${manifest.sourceKind}\`  `,
    `**Starter kit:** \`${manifest.starterKitId}\` @ \`${manifest.starterKitVersion}\`  `,
    `**Import mode:** \`${manifest.importMode}\``,
    ``,
    `## Source`,
    ``,
    sourceHeading(manifest),
    ``,
    `## Detection`,
    ``,
    detectionSection(manifest),
    ``,
    `## Security inspection`,
    ``,
    securitySection(manifest),
    ``,
    `## Next steps`,
    ``,
    nextStepsSection(manifest),
    ``,
    `---`,
    `Generated by the Growthub Source Import Agent. Canonical manifest lives at \`.growthub-fork/source-import.json\`.`,
    ``,
  ].join("\n");

  fs.mkdirSync(path.dirname(summaryPath), { recursive: true });
  fs.writeFileSync(summaryPath, body, "utf8");
  return summaryPath;
}
