/**
 * `growthub workspace portal` — Agency portal / client workspace helpers.
 *
 * Prepares a governed workspace for client-specific deployment by scaffolding
 * branding config, environment variable names, and a handoff document.
 * This is a scaffold/config helper — it does NOT create a multi-tenant runtime.
 *
 *   growthub workspace portal prepare --client <slug> [--json]
 *   growthub workspace portal prepare --client <slug> --out ./client-portal [--json]
 *   growthub workspace portal export --client <slug> [--json]
 *
 * All writes are deterministic and reversible. No network calls.
 */

import { Command } from "commander";
import * as p from "@clack/prompts";
import pc from "picocolors";
import fs from "node:fs";
import path from "node:path";
import { resolveInForkStateDir } from "../config/kit-forks-home.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function resolveClientSlug(raw: string): string {
  return slugify(raw);
}

interface ForkMeta {
  forkId?: string;
  kitId?: string;
}

function readForkMeta(forkPath: string): ForkMeta {
  const forkJsonPath = path.resolve(resolveInForkStateDir(forkPath), "fork.json");
  if (!fs.existsSync(forkJsonPath)) return {};
  try {
    return JSON.parse(fs.readFileSync(forkJsonPath, "utf8")) as ForkMeta;
  } catch {
    return {};
  }
}

function readWorkspaceConfig(forkPath: string): Record<string, unknown> {
  const candidates = [
    path.resolve(forkPath, "growthub.config.json"),
    path.resolve(forkPath, "apps/workspace/growthub.config.json"),
  ];
  for (const candidate of candidates) {
    if (!fs.existsSync(candidate)) continue;
    try {
      return JSON.parse(fs.readFileSync(candidate, "utf8")) as Record<string, unknown>;
    } catch {
      return {};
    }
  }
  return {};
}

// ---------------------------------------------------------------------------
// Portal prepare
// ---------------------------------------------------------------------------

export interface PortalPrepareResult {
  status: "ok" | "error";
  clientSlug: string;
  forkPath: string;
  outputPath: string;
  filesWritten: string[];
  envVarsNeeded: string[];
  deployChecklist: string[];
  nextCommand: string;
  error?: string;
}

function generateEnvVarNames(clientSlug: string): string[] {
  const upper = clientSlug.toUpperCase().replace(/-/g, "_");
  return [
    `GROWTHUB_WORKSPACE_ID`,
    `GROWTHUB_WORKSPACE_SLUG`,
    `${upper}_BRAND_NAME`,
    `${upper}_BRAND_LOGO_URL`,
    `${upper}_BRAND_PRIMARY_COLOR`,
    `DATABASE_URL`,
    `GROWTHUB_BRIDGE_ACCESS_TOKEN`,
  ];
}

function generateHandoffDoc(opts: {
  clientSlug: string;
  clientName: string;
  forkId?: string;
  kitId?: string;
  envVarNames: string[];
  outputPath: string;
}): string {
  return `# Client Portal Handoff — ${opts.clientName}

Generated by \`growthub workspace portal prepare --client ${opts.clientSlug}\`

---

## Workspace Details

- **Client slug:** \`${opts.clientSlug}\`
- **Fork ID:** \`${opts.forkId ?? "not registered"}\`
- **Kit:** \`${opts.kitId ?? "unknown"}\`
- **Output path:** \`${opts.outputPath}\`

---

## Required Environment Variables

Set these in your Vercel project or \`.env.local\`:

\`\`\`bash
${opts.envVarNames.map((v) => `${v}=`).join("\n")}
\`\`\`

---

## Deploy Checklist

1. Fill in all environment variables above
2. \`growthub workspace qa --json\` — verify workspace is build-ready
3. \`growthub workspace deploy check --json\` — verify deployment readiness
4. \`cd apps/workspace && npm install && npm run build\` — verify build passes
5. Deploy to Vercel: \`cd apps/workspace && vercel\`
6. \`growthub integrations status --json\` — verify integrations are live
7. Hand off dashboard URL + credentials to client

---

## Fork Sync

To pull upstream updates:
\`\`\`bash
growthub workspace upstream check --json
growthub workspace upstream heal --dry-run --json
growthub workspace upstream pr --json
\`\`\`

---

*Generated by Growthub Local CLI — docs/WORKSPACE_DEPLOY_FLOW.md*
`;
}

function generateBrandConfig(clientSlug: string, clientName: string): Record<string, unknown> {
  return {
    clientSlug,
    clientName,
    branding: {
      name: clientName,
      logoUrl: "",
      primaryColor: "#6366f1",
      accentColor: "#8b5cf6",
    },
    deploy: {
      platform: "vercel",
      appRoot: "apps/workspace",
    },
    generatedBy: "growthub workspace portal prepare",
    generatedAt: new Date().toISOString(),
  };
}

async function runPortalPrepare(opts: {
  client: string;
  fork?: string;
  out?: string;
  json?: boolean;
}): Promise<void> {
  const forkPath = opts.fork ? path.resolve(opts.fork) : process.cwd();
  const clientSlug = resolveClientSlug(opts.client);
  const clientName = opts.client;
  const outputPath = opts.out ? path.resolve(opts.out) : path.resolve(forkPath, `client-portals/${clientSlug}`);

  const forkMeta = readForkMeta(forkPath);
  const workspaceConfig = readWorkspaceConfig(forkPath);
  const envVarNames = generateEnvVarNames(clientSlug);

  const deployChecklist = [
    "Fill in all required env vars",
    "growthub workspace qa --json",
    "growthub workspace deploy check --json",
    "npm install && npm run build (in apps/workspace)",
    "Deploy to Vercel",
    "growthub integrations status --json",
  ];

  try {
    fs.mkdirSync(outputPath, { recursive: true });

    const filesWritten: string[] = [];

    // Write brand config
    const brandConfigPath = path.resolve(outputPath, "brand.config.json");
    fs.writeFileSync(
      brandConfigPath,
      `${JSON.stringify(generateBrandConfig(clientSlug, clientName), null, 2)}\n`,
      "utf8",
    );
    filesWritten.push(brandConfigPath.replace(forkPath, "."));

    // Write env template
    const envTemplatePath = path.resolve(outputPath, ".env.template");
    fs.writeFileSync(
      envTemplatePath,
      `# Environment variables for client: ${clientName} (${clientSlug})\n# Generated by growthub workspace portal prepare\n\n${envVarNames.map((v) => `${v}=`).join("\n")}\n`,
      "utf8",
    );
    filesWritten.push(envTemplatePath.replace(forkPath, "."));

    // Write handoff doc
    const handoffPath = path.resolve(outputPath, "HANDOFF.md");
    fs.writeFileSync(
      handoffPath,
      generateHandoffDoc({
        clientSlug,
        clientName,
        forkId: forkMeta.forkId,
        kitId: forkMeta.kitId,
        envVarNames,
        outputPath,
      }),
      "utf8",
    );
    filesWritten.push(handoffPath.replace(forkPath, "."));

    // Write growthub-portal-meta.json
    const metaPath = path.resolve(outputPath, "growthub-portal-meta.json");
    fs.writeFileSync(
      metaPath,
      `${JSON.stringify({
        clientSlug,
        clientName,
        forkId: forkMeta.forkId,
        kitId: forkMeta.kitId,
        workspaceId: workspaceConfig.workspaceId ?? null,
        outputPath,
        preparedAt: new Date().toISOString(),
      }, null, 2)}\n`,
      "utf8",
    );
    filesWritten.push(metaPath.replace(forkPath, "."));

    const result: PortalPrepareResult = {
      status: "ok",
      clientSlug,
      forkPath,
      outputPath,
      filesWritten,
      envVarsNeeded: envVarNames,
      deployChecklist,
      nextCommand: `growthub workspace deploy check --fork ${forkPath} --json`,
    };

    if (opts.json) {
      console.log(JSON.stringify(result, null, 2));
      return;
    }

    p.note(
      [
        `Client: ${clientName} (${clientSlug})`,
        `Output: ${outputPath}`,
        "",
        "Files written:",
        ...filesWritten.map((f) => `  ${f}`),
        "",
        "Env vars to configure:",
        ...envVarNames.map((v) => `  ${v}=`),
        "",
        "Next: growthub workspace deploy check --json",
      ].join("\n"),
      "Portal Prepared",
    );
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    if (opts.json) {
      console.log(JSON.stringify({ status: "error", clientSlug, forkPath, outputPath, error }));
      process.exitCode = 1;
      return;
    }
    console.error(pc.red(`Failed to prepare portal: ${error}`));
    process.exitCode = 1;
  }
}

// ---------------------------------------------------------------------------
// Portal export (scaffold copy for handoff)
// ---------------------------------------------------------------------------

async function runPortalExport(opts: {
  client: string;
  fork?: string;
  out?: string;
  json?: boolean;
}): Promise<void> {
  // Export = prepare + print summary. Workspace copy is out of scope for now.
  await runPortalPrepare(opts);
}

// ---------------------------------------------------------------------------
// Command registration
// ---------------------------------------------------------------------------

export function registerWorkspacePortalCommands(workspaceCmd: Command): void {
  const portal = workspaceCmd
    .command("portal")
    .description("Agency portal helpers — prepare and export client workspace configs");

  portal
    .command("prepare")
    .description("Scaffold a client-specific portal config, env template, and handoff doc")
    .requiredOption("--client <slug>", "Client name or slug (e.g. acme-corp)")
    .option("--fork <path>", "Fork root path (default: cwd)")
    .option("--out <path>", "Output directory (default: client-portals/<slug> under fork root)")
    .option("--json", "Emit machine-readable JSON")
    .addHelpText("after", `
Examples:
  $ growthub workspace portal prepare --client acme-corp
  $ growthub workspace portal prepare --client acme-corp --json
  $ growthub workspace portal prepare --client acme-corp --out ./acme-portal --json

JSON shape:
  { status, clientSlug, forkPath, outputPath, filesWritten, envVarsNeeded, deployChecklist, nextCommand }

Docs: docs/WORKSPACE_DEPLOY_FLOW.md
`)
    .action(async (opts: { client: string; fork?: string; out?: string; json?: boolean }) => {
      await runPortalPrepare(opts);
    });

  portal
    .command("export")
    .description("Export client portal scaffold (alias for prepare + handoff summary)")
    .requiredOption("--client <slug>", "Client name or slug")
    .option("--fork <path>", "Fork root path (default: cwd)")
    .option("--out <path>", "Output directory")
    .option("--json", "Emit machine-readable JSON")
    .addHelpText("after", `
Examples:
  $ growthub workspace portal export --client acme-corp --json
`)
    .action(async (opts: { client: string; fork?: string; out?: string; json?: boolean }) => {
      await runPortalExport(opts);
    });
}
