/**
 * cli/src/templates/catalog.ts
 *
 * Static slug registry — pure typed data, no FS, no imports from other CLI modules.
 *
 * To add a template: add entry here. Nothing else changes.
 * To add a family:   add entries with new family value + add to TemplateFamily in contract.ts.
 */

import type { AdFormatArtifact, SceneModuleArtifact, MarketingFrameworkArtifact, TemplateArtifact } from "./contract.js";

const AD_FORMATS: AdFormatArtifact[] = [
  {
    type: "ad-format",
    slug: "bedroom-minimic-talk",
    id: "ad-formats/bedroom-minimic-talk",
    name: "Bedroom Mini-Mic Talk",
    family: "video-creative",
    category: "Skincare / Beauty Tech / Consumer Product",
    tags: ["ugc", "skincare", "beauty-tech", "tiktok", "23s", "proven"],
    scenes: 6,
    hookVariations: 5,
    compatibleFormats: [],
    frozen: true,
    path: "ad-formats/bedroom-minimic-talk.md",
  },
  {
    type: "ad-format",
    slug: "villain-animation",
    id: "ad-formats/villain-animation",
    name: "Villain Object Animation",
    family: "video-creative",
    category: "Pet / Home / Supplement / Displacement products",
    tags: ["animated", "villain", "long-form", "agitation-stack", "proven"],
    scenes: 9,
    hookVariations: 5,
    compatibleFormats: [],
    frozen: true,
    path: "ad-formats/villain-animation.md",
  },
  {
    type: "ad-format",
    slug: "process-specialist-medical",
    id: "ad-formats/process-specialist-medical",
    name: "The Process Specialist",
    family: "video-creative",
    category: "Medical / Regenerative Medicine / Healthcare Authority",
    tags: ["medical", "authority", "doctor", "ugc", "50s", "proven"],
    scenes: 5,
    hookVariations: 5,
    compatibleFormats: [],
    frozen: true,
    path: "ad-formats/process-specialist-medical.md",
  },
  {
    type: "ad-format",
    slug: "frame-analysis",
    id: "ad-formats/frame-analysis",
    name: "Frame-by-Frame Analysis Methodology",
    family: "video-creative",
    category: "Methodology — use when no frozen format matches a muse",
    tags: ["methodology", "muse", "frame-extraction"],
    scenes: null,
    hookVariations: null,
    compatibleFormats: [],
    frozen: true,
    path: "ad-formats/frame-analysis.md",
  },
];

const HOOKS: SceneModuleArtifact[] = [
  {
    type: "scene-module", subtype: "hook",
    slug: "meme-overlay",
    id: "scene-modules/hooks/meme-overlay",
    name: "Meme Overlay Hook",
    family: "video-creative",
    category: "Relatable lifestyle pain — tired, stressed, broke",
    tags: ["meme", "scene-1", "scroll-stop", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk"],
    path: "scene-modules/hooks/meme-overlay.md",
  },
  {
    type: "scene-module", subtype: "hook",
    slug: "tiktok-comment",
    id: "scene-modules/hooks/tiktok-comment",
    name: "TikTok Comment Hook",
    family: "video-creative",
    category: "High-skepticism categories — objection-first open",
    tags: ["tiktok-comment", "scene-1", "skepticism", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk"],
    path: "scene-modules/hooks/tiktok-comment.md",
  },
  {
    type: "scene-module", subtype: "hook",
    slug: "pov-confession",
    id: "scene-modules/hooks/pov-confession",
    name: "POV Mirror Confession Hook",
    family: "video-creative",
    category: "Skincare / Beauty — female 25–35 demo",
    tags: ["pov", "mirror", "scene-1", "tiktok", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk"],
    path: "scene-modules/hooks/pov-confession.md",
  },
  {
    type: "scene-module", subtype: "hook",
    slug: "dollar-amount",
    id: "scene-modules/hooks/dollar-amount",
    name: "Dollar Amount Confession Hook",
    family: "video-creative",
    category: "Any category where overspending is the shared pain",
    tags: ["dollar-amount", "scene-1", "cross-format", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk", "villain-animation"],
    path: "scene-modules/hooks/dollar-amount.md",
  },
  {
    type: "scene-module", subtype: "hook",
    slug: "villain-hook",
    id: "scene-modules/hooks/villain-hook",
    name: "Villain Character Hook",
    family: "video-creative",
    category: "Animated — product displacing an incumbent",
    tags: ["villain", "animated", "scene-1", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["villain-animation"],
    path: "scene-modules/hooks/villain-hook.md",
  },
];

const BODY: SceneModuleArtifact[] = [
  {
    type: "scene-module", subtype: "body",
    slug: "minimic-problem",
    id: "scene-modules/body/minimic-problem",
    name: "Mini-Mic Problem Confession",
    family: "video-creative",
    category: "Authority + failed solutions — Scene 2",
    tags: ["minimic", "scene-2", "authority", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk"],
    path: "scene-modules/body/minimic-problem.md",
  },
  {
    type: "scene-module", subtype: "body",
    slug: "tiktok-skeptic-pivot",
    id: "scene-modules/body/tiktok-skeptic-pivot",
    name: "TikTok Skeptic Pivot",
    family: "video-creative",
    category: "Skeptic disarm + product intro — Scene 3",
    tags: ["tiktok-comment", "scene-3", "skeptic", "pivot", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk"],
    path: "scene-modules/body/tiktok-skeptic-pivot.md",
  },
  {
    type: "scene-module", subtype: "body",
    slug: "product-demo-glow",
    id: "scene-modules/body/product-demo-glow",
    name: "Product Demo — Glow / Active Effect",
    family: "video-creative",
    category: "Products with a visible active state — Scene 4",
    tags: ["demo", "scene-4", "glow", "active-state", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk"],
    path: "scene-modules/body/product-demo-glow.md",
  },
  {
    type: "scene-module", subtype: "body",
    slug: "villain-agitation",
    id: "scene-modules/body/villain-agitation",
    name: "Villain Agitation Stack",
    family: "video-creative",
    category: "4× stacked failed solutions — Scenes 2–5",
    tags: ["villain", "agitation", "scenes-2-5", "animated", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["villain-animation"],
    path: "scene-modules/body/villain-agitation.md",
  },
  {
    type: "scene-module", subtype: "body",
    slug: "before-after-flatlay",
    id: "scene-modules/body/before-after-flatlay",
    name: "Before/After + Product Flat Lay",
    family: "video-creative",
    category: "Social proof + product authority — Scene 5",
    tags: ["before-after", "flatlay", "scene-5", "social-proof", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk"],
    path: "scene-modules/body/before-after-flatlay.md",
  },
];

const CTA: SceneModuleArtifact[] = [
  {
    type: "scene-module", subtype: "cta",
    slug: "bogo-meme-bookend",
    id: "scene-modules/cta/bogo-meme-bookend",
    name: "BOGO + Meme Bookend Close",
    family: "video-creative",
    category: "BOGO / % off / flash offer — Scene 6",
    tags: ["bogo", "meme-bookend", "cta", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["bedroom-minimic-talk"],
    path: "scene-modules/cta/bogo-meme-bookend.md",
  },
  {
    type: "scene-module", subtype: "cta",
    slug: "guarantee-close",
    id: "scene-modules/cta/guarantee-close",
    name: "Guarantee Calendar Close",
    family: "video-creative",
    category: "30/60-day satisfaction guarantee — Scene 9",
    tags: ["guarantee", "calendar", "cta", "animated", "proven"],
    scenes: null, frozen: true,
    compatibleFormats: ["villain-animation"],
    path: "scene-modules/cta/guarantee-close.md",
  },
];

const MARKETING_FRAMEWORKS: MarketingFrameworkArtifact[] = [
  {
    type: "marketing-framework",
    slug: "cro-7-dimensions",
    id: "marketing-frameworks/cro-7-dimensions",
    name: "CRO Analysis — 7 Dimensions",
    family: "marketing-framework",
    category: "Conversion Optimization",
    tags: ["cro", "conversion", "landing-page", "audit", "scoring"],
    sourceSkill: "page-cro",
    frozen: true,
    path: "marketing-frameworks/cro-7-dimensions.md",
  },
  {
    type: "marketing-framework",
    slug: "seo-audit-eeat",
    id: "marketing-frameworks/seo-audit-eeat",
    name: "SEO Audit — E-E-A-T Framework",
    family: "marketing-framework",
    category: "SEO & Discovery",
    tags: ["seo", "eeat", "audit", "technical-seo", "content-quality"],
    sourceSkill: "seo-audit",
    frozen: true,
    path: "marketing-frameworks/seo-audit-eeat.md",
  },
  {
    type: "marketing-framework",
    slug: "email-sequence-architecture",
    id: "marketing-frameworks/email-sequence-architecture",
    name: "Email Sequence — 5-Type Architecture",
    family: "marketing-framework",
    category: "Email & Retention",
    tags: ["email", "sequence", "nurture", "welcome", "retention"],
    sourceSkill: "email-sequence",
    frozen: true,
    path: "marketing-frameworks/email-sequence-architecture.md",
  },
  {
    type: "marketing-framework",
    slug: "product-marketing-context",
    id: "marketing-frameworks/product-marketing-context",
    name: "Product Marketing Context — Foundation",
    family: "marketing-framework",
    category: "Strategy & Foundation",
    tags: ["context", "positioning", "audience", "brand-voice", "foundation"],
    sourceSkill: "product-marketing-context",
    frozen: true,
    path: "marketing-frameworks/product-marketing-context.md",
  },
  {
    type: "marketing-framework",
    slug: "launch-playbook",
    id: "marketing-frameworks/launch-playbook",
    name: "Launch Strategy — Phased Playbook",
    family: "marketing-framework",
    category: "Growth & Launch",
    tags: ["launch", "gtm", "go-to-market", "playbook", "checklist"],
    sourceSkill: "launch-strategy",
    frozen: true,
    path: "marketing-frameworks/launch-playbook.md",
  },
  {
    type: "marketing-framework",
    slug: "competitor-positioning",
    id: "marketing-frameworks/competitor-positioning",
    name: "Competitor Analysis — Positioning Gaps",
    family: "marketing-framework",
    category: "Strategy & Foundation",
    tags: ["competitor", "positioning", "alternatives", "feature-matrix"],
    sourceSkill: "competitor-alternatives",
    frozen: true,
    path: "marketing-frameworks/competitor-positioning.md",
  },
];

/** Master catalog. Append new family arrays below. */
export const TEMPLATE_CATALOG: readonly TemplateArtifact[] = [
  ...AD_FORMATS,
  ...HOOKS,
  ...BODY,
  ...CTA,
  ...MARKETING_FRAMEWORKS,
  // ...EMAIL_TEMPLATES,
  // ...MOTION_TEMPLATES,
] as const;

