import type { Kit } from "./types";

export const mockKits: Kit[] = [
  {
    id: "creative-strategist-v1",
    name: "Creative Strategist",
    description: "Frozen Creative Strategist worker kit for exporting a working-directory-ready video creative brief worker with ad formats, scene modules, and brand templates.",
    version: "1.0.0",
    author: {
      username: "growthub",
      displayName: "Growthub",
    },
    complexity: "moderate",
    type: "worker",
    featured: true,
    publishedAt: "2026-04-09T00:00:00.000Z",
    updatedAt: "2026-04-09T00:00:00.000Z",
    tags: ["GTM", "Creative", "Video", "Marketing"],
    executionMode: "export",
    activationModes: ["export"],
  },
  {
    id: "code-review-v1",
    name: "5-Pass Code Review",
    description: "Systematic code review protocol with 5 passes: correctness, security, performance, readability, and consistency. Every finding includes file, line, severity, and fix recommendation.",
    version: "1.0.0",
    author: {
      username: "citadel",
      displayName: "Citadel",
    },
    complexity: "easy",
    type: "worker",
    featured: true,
    publishedAt: "2026-04-08T10:00:00.000Z",
    updatedAt: "2026-04-08T10:00:00.000Z",
    tags: ["DX", "Quality", "Review"],
    executionMode: "run",
    activationModes: ["run"],
  },
  {
    id: "codebase-map-v1",
    name: "Codebase Intelligence Map",
    description: "Build structural codebase index with files, exports, imports, dependency graph, and roles. Enables keyword search and compact slices for agent context injection.",
    version: "1.0.0",
    author: {
      username: "citadel",
      displayName: "Citadel",
    },
    complexity: "easy",
    type: "workflow",
    featured: true,
    publishedAt: "2026-04-08T09:00:00.000Z",
    updatedAt: "2026-04-08T09:00:00.000Z",
    tags: ["DX", "Intelligence", "Mapping"],
    executionMode: "install",
    activationModes: ["install", "run"],
  },
  {
    id: "memory-engine-v1",
    name: "Persistent Memory Engine",
    description: "Persistent memory engine for AI agents with graph-first retrieval, contradiction tracking, temporal decay, and 3D brain visualization.",
    version: "0.3.0",
    author: {
      username: "lalomorales",
      displayName: "Lalo Morales",
    },
    complexity: "easy",
    type: "worker",
    featured: true,
    publishedAt: "2026-04-07T15:00:00.000Z",
    updatedAt: "2026-04-07T15:00:00.000Z",
    tags: ["Memory", "AI", "Graph"],
    executionMode: "install",
    activationModes: ["install"],
  },
  {
    id: "systematic-debug-v1",
    name: "Systematic Debugging Protocol",
    description: "4-phase debug protocol: observe, hypothesize, verify, and fix. No code changes without a confirmed root cause. Includes emergency stop after two failed attempts.",
    version: "1.0.0",
    author: {
      username: "citadel",
      displayName: "Citadel",
    },
    complexity: "easy",
    type: "worker",
    featured: false,
    publishedAt: "2026-04-06T12:00:00.000Z",
    updatedAt: "2026-04-06T12:00:00.000Z",
    tags: ["DX", "Debugging", "Quality"],
    executionMode: "run",
    activationModes: ["run"],
  },
  {
    id: "structured-research-v1",
    name: "Structured Research Kit",
    description: "Transform questions into findings with confidence levels and citations. Performs 2-4 queries across 3-6 sources with persistent documentation.",
    version: "1.0.0",
    author: {
      username: "citadel",
      displayName: "Citadel",
    },
    complexity: "easy",
    type: "workflow",
    featured: false,
    publishedAt: "2026-04-05T08:00:00.000Z",
    updatedAt: "2026-04-05T08:00:00.000Z",
    tags: ["Research", "Intelligence"],
    executionMode: "run",
    activationModes: ["run"],
  },
  {
    id: "autonomous-quality-v1",
    name: "Autonomous Quality Loop",
    description: "Scores against a rubric, attacks the highest-leverage axis, verifies no regressions, documents learnings, and loops. Re-scores from scratch each iteration.",
    version: "1.0.0",
    author: {
      username: "citadel",
      displayName: "Citadel",
    },
    complexity: "moderate",
    type: "worker",
    featured: false,
    publishedAt: "2026-04-04T14:00:00.000Z",
    updatedAt: "2026-04-04T14:00:00.000Z",
    tags: ["Quality", "Automation", "Testing"],
    executionMode: "run",
    activationModes: ["run"],
  },
  {
    id: "project-scaffold-v1",
    name: "Project-Aware Scaffold",
    description: "Reads your codebase, finds exemplars, generates new files matching exact conventions, and wires into every registration point. No generic templates.",
    version: "1.0.0",
    author: {
      username: "citadel",
      displayName: "Citadel",
    },
    complexity: "easy",
    type: "worker",
    featured: false,
    publishedAt: "2026-04-03T11:00:00.000Z",
    updatedAt: "2026-04-03T11:00:00.000Z",
    tags: ["DX", "Scaffolding", "Code Generation"],
    executionMode: "run",
    activationModes: ["run"],
  },
];
